### PR TITLE
BLD: Adds versioneer

### LINKED ISSUE #216: Add versioneer

### PR DESCRIPTION
**Pull request by llllllllll**
closes #216

### CODE REVIEW

**Comment by richafrank** [comment]
Awesome!  What's the change with the travis emails?

**Comment by llllllllll** [comment]
every time travis runs your branch it emails you the response. I personally dislike this behavior. if we don't to disable it that is fine

**Comment by twiecki** [comment]
Looks great. Kinda unfortunate we have to save versioneer.py in the repo itself. +1 on not emailing.

**Comment by richafrank** [comment]
Looks good to me then.  Agreed @twiecki - I suppose it needs to be bootstrapped somehow...

**Comment by twiecki** [comment]
Merged with https://github.com/quantopian/pyfolio/commit/3f11250c932ff023ba96d3530e0eff88a2afa96b. Thanks @llllllllll and @richafrank.

**Comment by llllllllll** [comment]
> Kinda unfortunate we have to save versioneer.py in the repo itself.
This is how versioneer is intended to be used. The `versioneer install` script vendors itself into the project.

**Pull request closed without merging**
