### PR TITLE
MAINT Change format of cached SPY and Fama-French factors to csv inst…

### PR DESCRIPTION
**Pull request by twiecki**
…ead of hdf. Also fixes some more UTC issues.

### CODE REVIEW

**Comment by twiecki** [comment]
The reason I changed it is because we ran into this issue: https://github.com/pydata/pandas/issues/8165

Also removes pytables as a dependency.

**Comment by gusgordon** [comment]
Interesting, looks great to me.

**Comment by gusgordon** [comment]
I think this is made redundant by #120?

**Comment by twiecki** [comment]
Thanks for reviewing @gusgordon! Yeah, that branch is based off of this one.

**Pull request merged**
