### PR TITLE
Fixed notebooks (and updated symlinks)

### PR DESCRIPTION
**Pull request by eigenfoo**
Picking off work on #411: fixed symlinks in the `docs` directory (don't have write access to pyfolio, so this is on a branch). This is a merge into a branch; the branch itself will need to be merged to master.

cc @twiecki

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks @eigenfoo!

**Comment by eigenfoo** [comment]
@twiecki you only merged the PR to the `fix_nbs` branch of pyfolio, not to master

**Comment by twiecki** [comment]
Oh, weird.

**Comment by twiecki** [comment]
https://github.com/quantopian/pyfolio/pull/424

**Pull request merged**
