### PR TITLE
Fix example notebooks

### LINKED ISSUE #410: Example notebooks don't work
Some of the example notebooks are saved with the correct graphical output, but throw an error when you actually try to run the cells. We should definitely clean this up to make it easier for people to learn how to use pyfolio.

### PR DESCRIPTION
**Pull request by eigenfoo**
Fixes #410

### CODE REVIEW

**Comment by twiecki** [comment]
I don't think this NB should be here in the first place and we should delete it.

**Comment by georgh0021** [comment]
I'm also cleaning up the other notebooks: some are very old, and are throwing errors because pyfolio has changed so much. Will delete the linear algebra tests notebook, though.

**Comment by georgh0021** [comment]
Two issues: the pyfolio talk slides have the same picture for a "traditional hedge fund" and "crowd-sourced hedge fund", so we embarrassingly just liken ourselves to a normal hedge fund. Contacted marketing for the slides.

Also, the zipline example notebook is now broken due to changes like the yahoo data reader. Contacted academia for someone with more experience with zipline to rewrite the notebook.

**Comment by georgh0021** [comment]
Fixed the hedge fund pngs in the pyfolio talk slide. Just waiting on the zipline example notebook from @nathanwolfe now.

**Comment by georgh0021** [comment]
Notebooks all cleaned up

@twiecki @richafrank requesting review and sign off (no changes to API or dependencies)

**Comment by twiecki** [comment]
Looks great. You also need to fix the links in https://github.com/quantopian/pyfolio/tree/master/docs/notebooks.

**Comment by richafrank** [comment]
Looks safe from my end. 👍

**Comment by gusgordon** [comment]
This is great!

For the zipline example maybe we can use the newer IPython magic: https://github.com/quantopian/zipline/blob/master/zipline/examples/buyapple.ipynb

Also, trying to think if there's any way we can de-clutter this further. If people are first looking at pyfolio and want an example, it's not going to be obvious to them which notebook gives the best general overview. I wonder if there's a way we can combine a few of the notebooks or something.

**Comment by georgh0021** [comment]
I believe we are using the `%load_ext` magic, but I might not be the best person to talk to about this... @nathanwolfe might be able to help here.

About decluttering: the notebooks don't have very many cells, it's just the tear sheets themselves that are taking up the space... I actually think that combining notebooks would make it harder to figure out what's going on. Perhaps we should just name the notebooks more descriptively?

**Comment by eigenfoo** [comment]
This PR is ready to merge btw

**Comment by twiecki** [comment]
What about https://github.com/quantopian/pyfolio/pull/411#issuecomment-322171642?

**Comment by eigenfoo** [comment]
Completely forgot! I made a new PR for that

**Pull request merged**
