### PR TITLE
replaced yahoo backend with google for market data

### PR DESCRIPTION
**Pull request by closedLoop**
Referencing issue: #385 

I have substituted out the yahoo backend for the google data using the pandas `web.get_data_google(symbol, start=start, end=end)` function

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks @closedLoop. Do they offer the same time-range?

**Comment by closedLoop** [comment]
@twiecki I quick look at it has SPY since 1993.  However, it looks like the API only returns the last 4000 days for any given range.

**Comment by twiecki** [comment]
@closedLoop Yeah, that's how I remember google finance to work. I'd rather wait a few more days for pandas-datareader to fix the issue and update rather than switch the source. Appreciate the initiative though.

**Comment by twiecki** [comment]
Actually it seems that yahoo is discontinuing its service in which case we would need to switch to google.

**Comment by gusgordon** [comment]
Thanks for the PR. Looks like Travis is spitting out this error:
```
======================================================================
ERROR: Failure: ImportError (cannot import name PandasError)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/__init__.py", line 3, in <module>
    from . import utils
  File "/home/travis/build/quantopian/pyfolio/pyfolio/utils.py", line 27, in <module>
    from pandas_datareader import data as web
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas_datareader/data.py", line 7, in <module>
    from pandas_datareader.google.daily import GoogleDailyReader
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas_datareader/google/daily.py", line 1, in <module>
    from pandas_datareader.base import _DailyBaseReader
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas_datareader/base.py", line 11, in <module>
    from pandas.core.common import PandasError, is_number
ImportError: cannot import name PandasError
```

Looks like this is a pandas issue between `0.19` and `0.20`: https://stackoverflow.com/questions/43809620/importerror-cannot-import-name-pandaserror

I'm guessing you are on `0.20` @closedLoop ?

**Comment by twiecki** [comment]
Yeah we need to fix that urgently.

**Comment by FreddieV4** [comment]
Hi @closedLoop, are you going to continue working on this PR 🙂  ?

**Comment by closedLoop** [comment]
Sure I can adjust this.  Which version of pandas should this support?

**Comment by gusgordon** [comment]
Thanks. Ideally, it should support 0.18, .19, and .20. Also note that we only want to fall back to Google if the Yahoo fetching fails, because Google's prices aren't adjusted for splits and dividends.

**Comment by closedLoop** [comment]
Do you want it to raise a warning of any kind?

Please excuse any typos as this was sent from a mobile device.

**Comment by gusgordon** [comment]
Good idea. Maybe @twiecki or others have other thoughts, but I think we can just wrap Yahoo in a try/except all, then emit a warning and fall back to Google.

**Comment by twiecki** [comment]
@closedLoop Yes, a warning would be perfect. I like the try/except approach as well.

**Comment by twiecki** [comment]
@closedLoop any progress?

**Comment by twiecki** [comment]
Forked and extended on https://github.com/quantopian/pyfolio/pull/395. Thanks @closedLoop.

**Pull request closed without merging**
