### PR TITLE
changed 252 to 252.0 so calendar returns are correct

### PR DESCRIPTION
**Pull request by ACampbell22**

### CODE REVIEW

**Comment by ssanderson** [comment]
Is the issue here that this is doing truncating integer division?  If so the right fix is to put `from __future__ import division` at the top of the file.

https://www.python.org/dev/peps/pep-0238/

**Comment by justinlent** [comment]
I closed this issue which was original #65 with this commit last night:  https://github.com/quantopian/pyfolio/commit/7f585f9cca08ade116c851804c6da592af8da064

**Comment by ssanderson** [comment]
@justinlent now that this is a public repo, we should *really* try to get out of the habit of pushing behavior changes directly to master.

Also, it looks like there's already a `__future__` division import in this file, which means the division here should have the exact same result regardless of the denominator here.  Can you guys show an example input where this is producing different results?

**Comment by justinlent** [comment]
all good. feel free to revert my commit and i'll work on a branch in the future

**Comment by ssanderson** [comment]
It's not worth changing at this point, but I'm still curious about why we think this changed any behavior.  As far as I can tell the change here is a no-op.

**Comment by ssanderson** [comment]
Consider, for example:
```
In [1]: from __future__ import division

In [2]: 5 / 3
Out[2]: 1.6666666666666667

In [3]: 5 / 3.0
Out[3]: 1.6666666666666667
```

**Comment by twiecki** [comment]
Agree with @ssanderson. https://github.com/quantopian/pyfolio/commit/38198f934ddfe9b74bae8506fb0a33d982707e89 implemented the right way to address this issue.

**Pull request closed without merging**
