### PR TITLE
Overlay OOS datapoints in boxplot

### PR DESCRIPTION
**Pull request by ahgnaw**
Point markers are diamonds instead of crosses.

### CODE REVIEW

**Comment by twiecki** [comment]
Looking at this code I think it's time to refactor it. Specifically,
```
    df_weekly = timeseries.aggregate_returns(returns, 'weekly')
    df_monthly = timeseries.aggregate_returns(returns, 'monthly')
```

Should happen inside the plotting function and only `returns` be passed in. The slicing is a bit confusing and this refactor could remedy this.

**Comment by ahgnaw** [comment]
@twiecki df_weekly and df_monthly are now only defined by the plotting functions that require them.

**Comment by twiecki** [comment]
LGTM, thanks!

**Comment by twiecki** [comment]
image

**Comment by twiecki** [comment]
@ahgnaw just noticed that we should probably add a legend as well explaining the red dots.

**Comment by ahgnaw** [comment]
image

Unfortunately matplotlib adds the line through the marker in the legend. What do you think of the text? Alternative: "Out-of-sample returns"

**Comment by twiecki** [comment]
```python
import matplotlib as mpl
mpl.rcParams['legend.handlelength'] = 0
```
Perhaps using that instead in a `rc_context`: http://matplotlib.org/api/matplotlib_configuration_api.html#matplotlib.rc_context

Also, the monthly color red is a bit hard to read with the red markers.

**Comment by twiecki** [comment]
I like out-of-sample data.

**Comment by ahgnaw** [comment]
image

I'll try out a few different colors. The daily, weekly, and monthly markers could each be different colors.

**Comment by twiecki** [comment]
I think we'd rather switch the red color of the last bar.

**Comment by ahgnaw** [comment]
image

image

here's yellow or green. I have a slight preference for the green, but either works.

**Comment by twiecki** [comment]
Sorry, I meant the actual fill color of the barplot, not the points.

**Comment by ahgnaw** [comment]
Ah ok. I think this last. It's changed to a yellow that is consistent with the color palette. Thoughts?

image

**Comment by twiecki** [comment]
Perfect.

**Pull request merged**
