### PR TITLE
STY Refactor to always pass functions full transactions instead of daily transaction volumes

### PR DESCRIPTION
**Pull request by ACampbell22**

### CODE REVIEW

**Comment by ACampbell22** [comment]
@twiecki Do you think we should try to merge this in before moving on to introducing the round trip code? I'd think that we'd want to start using this new convention ASAP so that the eventual merge of round trip stuff isn't painful.

**Comment by twiecki** [comment]
Yes definitely.

**Comment by ACampbell22** [comment]
I just tried and failed to rebase that single commit without pushing my new code.

**Comment by twiecki** [comment]
Ah, sorry. I missed that this was already making the initial change. Can you move the last commit to a different branch / PR? I want to review this one first separately.

**Comment by ACampbell22** [comment]
Ok, I think this should be good to go now. Shouldn't break travis once merged.

**Comment by twiecki** [comment]
OK, I rebased and force-pushed (please force-pull before making any changes to this branch).

**Comment by ACampbell22** [comment]
Thanks!

**Comment by twiecki** [comment]
LGTM, thanks.

**Pull request merged**
