### PR TITLE
REL: 0.8.1

### PR DESCRIPTION
**Pull request by yankees714**

### CODE REVIEW

**Comment by gusgordon** [comment]
Thanks - also: https://github.com/quantopian/pyfolio/pull/445

**Comment by gusgordon** [comment]
And maybe we can merge #444 first? Are there any other PRs that are almost done?

**Comment by yankees714** [comment]
@gusgordon I think @twiecki's thought was to get the expanded pandas support out ASAP: https://github.com/quantopian/pyfolio/pull/443#issuecomment-335274106. But happy to hold up if we're close on other stuff.

(Also thanks - will add #445 to whatsnew)

**Comment by twiecki** [comment]
Superseded by https://github.com/quantopian/pyfolio/pull/552.

**Pull request closed without merging**
