### PR TITLE
Fix issue #361

### PR DESCRIPTION
**Pull request by luca-s**
Fix issue #361

### CODE REVIEW

**Comment by georgh0021** [comment]
All checks failed with the same error message below. Please note that we enforce pep8 on the code base. You can test this on your computer by running `flake8 pyfolio` from the command line.

```
pyfolio/plotting.py:45:1: E302 expected 2 blank lines, found 1
pyfolio/plotting.py:54:17: E265 block comment should start with '# '
pyfolio/plotting.py:105:1: W293 blank line contains whitespace
```

**Comment by luca-s** [comment]
Oh right, PEP 8! I'll fix that

**Comment by twiecki** [comment]
Thanks @luca-s!

**Comment by georgh0021** [comment]
Thanks for your contribution @luca-s!

**Pull request merged**
