### PR TITLE
TST Install matplotlib-tests so that matplotlib can be unpegged. http…

### PR DESCRIPTION
**Pull request by twiecki**
…s://github.com/matplotlib/matplotlib/issues/5634

### CODE REVIEW

**Comment by twiecki** [comment]
Annoying voodo `ValueError: numpy.dtype has the wrong size, try recompiling` error again. https://github.com/conda/conda/issues/1701

**Comment by ssanderson** [comment]
@twiecki that error means that you have a C Extension that was compiled against an older version of numpy's headers than you have installed.  This can happen, for example, if you compile and install module X with numpy 1.9, and then subsequently install numpy 1.10 without recompiling module X.  It's unlikely that this is conda's fault.

**Comment by twiecki** [comment]
@ssanderson That's what I tried to look at but there shouldn't be any compilation going on as it's using conda to install everything.

**Comment by ssanderson** [comment]
I think this might actually be a zipline bug: https://github.com/quantopian/zipline/blob/master/setup.py#L225-L227

**Comment by ssanderson** [comment]
https://github.com/quantopian/zipline/issues/954

**Comment by twiecki** [comment]
@ssanderson zipline is indeed the problem (it works when I remove it from travis).

**Comment by ssanderson** [comment]
@twiecki you probably don't want to be unconditionally installing zipline master.  Are you depending on something ahead of the released 0.8.3 version?

**Comment by twiecki** [comment]
No. We might actually be able to drop it and just include the returns and positions data of a backtest into pyfolio.

**Comment by ssanderson** [comment]
> No. We might actually be able to drop it and just include the returns and positions data of a backtest into pyfolio.

I'd be nervous about doing this, since it will break if we change our output format.  I'd recommend just pip installing zipline==0.8.3 for now though.

**Comment by twiecki** [comment]
0.8.3 seems to have the same problem.

**Pull request merged**
