### PR TITLE
WIP Add cents-per-share calculation.

### PR DESCRIPTION
**Pull request by twiecki**
WIP -- DO NOT MERGE

Implements https://github.com/quantopian/pyfolio/issues/203

The issue is that it requires PnL which we do not use anywhere. We could compute it from returns and capital base, but we don't use capital base anywhere either. So here I'm then computing it by summing up the daily positions. Not sure that's the best way to go about doing this.

Ideas?

### CODE REVIEW

**Comment by justinlent** [comment]
Not sure what the original discussion was surrounding this metric, but I think this should be based purely on the buy/sell _transactions_.  So we have to choose either FIFO or LIFO  (I would probably choose FIFO) and than match roundturn transactions based on it.  and the cents-per-share calculation is just the net difference between the buy/sell FIFO mapped roundturn transactions.

Do you think that makes sense?

**Comment by twiecki** [comment]
Do you mean to tack this on to the round-trip analysis then? It seems like we could calculate this more easily by just averaging the PnL / #shares traded.

**Comment by justinlent** [comment]
Yea I think your approach makes sense of PnL/#shares traded.  Tacking onto roundtrip analysis seems like a great place for this. If it's easy to describe, how is what you've implemented in this branch different from just PnL/Shares traded?

**Comment by twiecki** [comment]
That's what it's supposed to compute.

**Comment by twiecki** [comment]
Closing for the time being. Will reopen when I have tests.

**Pull request closed without merging**
