### PR TITLE
remove old data loaders from utils, and migrate to empyrical

### PR DESCRIPTION
**Pull request by jameschristopher**

### CODE REVIEW

**Comment by georgh0021** [comment]
@jameschristopher could you also cut the unit tests that test for the data loaders? Travis is throwing this one for `utils.default_returns_func`. There may be more though...

```
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'default_returns_func')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/__init__.py", line 3, in <module>
    from . import utils
  File "/home/travis/build/quantopian/pyfolio/pyfolio/utils.py", line 164, in <module>
    'returns_func': empyrical.utils.default_returns_func
AttributeError: 'module' object has no attribute 'default_returns_func'
----------------------------------------------------------------------
Ran 1 test in 1.136s
FAILED (errors=1)
```

**Comment by jameschristopher** [comment]
pyfolio doesn't have tests for the util functions. This PR won't pass any of the tests until we bump the empyrical version so the above is to be expected

**Comment by twiecki** [comment]
@jameschristopher empyrical 0.3.2 is released.

**Comment by twiecki** [comment]
Thanks @jameschristopher. I forgot that we wanted to do a direct import of the functions in `pyfolio.utils`, can you do that? Also, we should `import empyrical as ep`.

**Comment by jameschristopher** [comment]
opened https://github.com/quantopian/pyfolio/pull/425 do you want me to refactor all empyrical references in pyfolio as `ep`?

**Pull request merged**
