### PR TITLE
Add tests for example NBs

### PR DESCRIPTION
**Pull request by twiecki**
* Add tests that run the NB files in the example folders and look for exceptions
* This revealed some issues that have been fixed with https://github.com/quantopian/pyfolio/pull/112 as well as in this PR. Mostly Python 3 compatibility issues.

Also caused some headaches because of a weird zipline installation issue, thus using `develop` install on travis.

### CODE REVIEW

**Comment by twiecki** [comment]
This is breaking because the examples aren't running without exception: https://github.com/quantopian/pyfolio/issues/110

**Comment by twiecki** [comment]
On travis we're seeing
```
ImportError                               Traceback (most recent call last)
<ipython-input-2-9adf7e5a0953> in <module>()
      9 
     10 # Import Zipline, the open source backtester
---> 11 from zipline import TradingAlgorithm
     12 from zipline.data.loader import load_bars_from_yahoo
     13 from zipline.api import order_target, symbol, history, add_history, schedule_function, date_rules, time_rules
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/zipline/__init__.py in <module>()
     23 __version__ = "0.8.0rc1"
     24 
---> 25 from . import data
     26 from . import finance
     27 from . import gens
ImportError: cannot import name data
```

No idea why.

**Comment by gusgordon** [comment]
Maybe NotebookRunner is doing something strange with the path?

**Comment by twiecki** [comment]
Good thinking, but also that works locally for me.

**Comment by twiecki** [comment]
OK, fixed after many tries. Someone want to take a look?

**Comment by gusgordon** [comment]
Looks good to me. Good to merge?

**Pull request merged**
