### PR TITLE
BUG: exposures should be averaged, not summed

### PR DESCRIPTION
**Pull request by vikram-narayan**

### CODE REVIEW

**Comment by Jstauth** [comment]
I think it would be helpful for this table to have a label describing the values. something like "Average Risk Factor Exposure" perhaps

**Comment by vikram-narayan** [comment]
sounds good, added that name to the exposures summary

**Comment by vikram-narayan** [comment]
@twiecki could you take a quick look and let me know if it's ok for me to merge?

**Comment by vikram-narayan** [comment]
👍  will squash commits and merge

**Pull request merged**
