### PR TITLE
[ENH] Switch regressions to use the pandas implementation

### PR DESCRIPTION
**Pull request by twiecki**
There were several different methods to calculate regressions
being used. We should use a consistent method everywhere
and Pandas does fast rolling regressions with all sorts of
bells and whistles.

### CODE REVIEW

**Comment by humdings** [comment]
I have some questions/concerns about our regression calculations before I do more work on this.

1. I am thinking we should return fitted ols objects rather than just the parameters everywhere. There's a lot of information we are throwing out by returning the parameters alone. Maybe we can break regression into a single function that is called by all the others to make sure we alway have access to the original object. Does anybody have an opinion on this.

2. We seen to use/return an intercept in some regression cases but not others. Are there any cases where we do not want to use intercepts to perform a regression?

3. I think 2 has caused some test cases to break or be written incorrectly, I plan to fix them up here as well.

**Comment by twiecki** [comment]
@humdings I agree with all your points. My only concern regarding returning 1. is usability and principle of least surprise (and returning an object rarely is not surprising). Maybe there's a way to have both though but I can't think of something I like..

**Comment by gusgordon** [comment]
Are we going to get this in for the release?

**Comment by twiecki** [comment]
I think this one is optional.

**Comment by humdings** [comment]
bump!

Bringing this back up. I think we can include this in the initial ship. It's a pretty simple change that
just standardizes the functions used to perform regressions.

I removed the kwarg to return the model from each of the functions, but I do think having functions
available that do return the model are important. 

This still requires test rewrites which is why travis fails.

**Comment by gusgordon** [comment]
OK, a lot of flake8 errors here have been fixed, and there are going to be merge conflicts here. Maybe it makes sense to reset this branch and just make the changes necessary from there? Let me know if you want me to do anything, too.

**Comment by twiecki** [comment]
@gusgordon That's probably the best way forward.

**Comment by MatthewGilbert** [comment]
Just thought I would add this in https://github.com/pydata/pandas/issues/6077. At some point pandas hopes to move the stats stuff to statsmodels and deprecate it, although as of now I don't believe there is any fast rolling or expanding OLS stuff in statsmodels.

**Comment by twiecki** [comment]
Thanks @MatthewGilbert, good to know.

**Comment by twiecki** [comment]
Closing due to inactivity. Hopefully we can implement this at a later point.

**Pull request closed without merging**
