### PR TITLE
STY standardize plotting styles

### LINKED ISSUE #256: Make colors differentiable
Right now it is hard to see the difference between some line colors in the sector allocation plot. Brighter and darker colors might help.

### LINKED ISSUE #415: Standardize style (axis, legend, labels, capitalization, ...) across all plots
Currently, pyfolio is a jumble of styles. Different plots have different looking legends, some plots don't have their labels capitalized, etc. Some differing style is obviously fine, but we should adopt a basic standard that is used in new plots.

I don't think this will too much effort — the bulk is just standardizing the legends, I believe. I'm not sure if breaking out some `style_plot` function is the answer, because there will be small differences between plots.

Things I can think of:
- Capitalize plot titles/legends/axis labels correctly
- Ensure proper rotation of axis labels
- Standardize legend style (I'm personally a fan of the transparent background-box)
- Standardize font sizes (might already be done)

### PR DESCRIPTION
**Pull request by eigenfoo**
Closes #415 and closes #256 

Here's what I've done:
- Capitalize plot titles/legends/axis labels correctly
    - For titles, legends and labels, capitalize only the first letter of the first word. No other capitalizations unless its a proper noun/acronym (specifically: Sharpe, Bayesian, PnL)
- Ensure proper rotation of axis labels
    - No rotation at all, unless the labels overlap
- Standardize legend style (I'm personally a fan of the transparent background-box)
    - All legends should have `frameon=True, framealpha=0.5`
- Standardize font sizes (might already be done)
    - Always use matplotlib defaults. Never manually set font sizes.

To-do:
- [x] Fix colors. Always use matplotlib named colors or color palettes. At no point should we be using our own hex RGB values.
- [x] Run a full tear sheet on an example and actually see if the style actually looks nice.

Notes:
- Removed `plot_monthly_returns_timeseries`, `plot_returns_similarity` and `plot_multistrike_cones` from `plotting.py`. They don't show up in any other module, so I'm not sure what they're doing there. If we actually do need them, I made them separate commits so we can safely revert them.
- Also did some minor formatting for readability

Not yet actually ready for review yet btw, just wanted to run a travis build so I'm sure that deleting those 3 functions doesn't actually mess anything up. I'll request reviews when ready :)

### CODE REVIEW

**Comment by gusgordon** [comment]
Nice! Would you mind posting a couple screenshots of sample plots with the new legend? What's your opinion on how it looks?

**Comment by eigenfoo** [comment]
I haven't actually tested it out yet! I'll do that once I fix the colors, which will be probably the day after tomorrow.

**Comment by eigenfoo** [comment]
Also while we're at it, all `fill_between` should have `alpha=0.4`. It would be nice to have the edge have a slightly higher alpha value, but that's rather complicated and not for right now.

**Comment by twiecki** [comment]
This looks great. Agree with @gusgordon, should update the Notebooks and see what the changes look like.

**Comment by eigenfoo** [comment]
Yes, thats a good idea. Unfortunately, the `full_tear_sheet_example` notebook must be run on Q research environment, since it uses a backtest object to create a full tear sheet. I can't run my PR version of pyfolio on research. Is it possible for someone at Q to do this? I'll take care of the rest.

Can I also suggest deleting the `portfolio_volatility_weighted_example` notebook? It illustrates portfolio allocation strategies, not how to actually use pyfolio. Academia might find it useful, but it doesn't really belong in pyfolio documentation.

**Comment by twiecki** [comment]
We can just leave that one for now but update the other ones. And yes, agreed about deleting the vol-weighted NB.

**Comment by eigenfoo** [comment]
FYI: the issue with #256 was not that we are using indistinguishable colors, it is that we are setting `alpha` to be too low. Someone must have decided to use a low alpha for e.g. the sector allocation plot because there are so many lines being plotted at once.

From now on:
Try not to lower alpha: it defaults to `1.0`
If there is a genuine concern that we will be unable to distinguish lines, use `alpha=0.6`

**Comment by eigenfoo** [comment]
In the meantime, here are some screenshots of what the newest style looks like:
screen shot 2017-08-23 at 11 53 24 am
screen shot 2017-08-23 at 12 16 01 pm
screen shot 2017-08-23 at 12 30 33 pm

**Comment by eigenfoo** [comment]
Also removed 2 pngs from the `examples` directory. Not sure what they were doing there.

**Comment by twiecki** [comment]
Nice, this looks much better! Ready to merge?

**Comment by eigenfoo** [comment]
@twiecki yes! 

I'm not very experienced with zipline, so I can't fix up the zipline example notebook. I'll file a separate issue for that though, I think there's enough in this PR to merge as it is.

**Comment by twiecki** [comment]
Thanks @eigenfoo!

**Comment by yankees714** [comment]
@eigenfoo We're currently using `plot_multistrike_cones` in an internal project, should we add it back before https://github.com/quantopian/pyfolio/pull/427?

**Comment by twiecki** [comment]
@yankees714 I don't think that code is used currently? Let's chat offline.

**Pull request merged**
